spring:
  kafka:
    consumer:
      group-id: ms_mail_consumer
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  mail:
    host: 207.130.19.136
    port: 25
    username: sandeep_vadde@hna.honda.com
    password: 